.TH magicedit 1 "September 2024" "magicedit 0.1" "User Commands"
.SH NAME
magicedit \- experimental code editor
.SH SYNOPSIS
.B magicedit
[\-options] [arguments]
.SH DESCRIPTION
.B magicedit
is an experimental code editor. It's highly inspired by tools like Acme and Vim.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help message.
.TP
.B \-v, \-\-version
Show version information.
.SH EXAMPLES
.B magicedit example.txt
.SH AUTHOR
Written by Berkay Çubuk<berkay@berkaycubuk.com>.
